# Generated by Django 4.2.2 on 2023-06-13 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('break_time', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('total_hours', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('mobile_no', models.CharField(max_length=12)),
                ('designation', models.CharField(max_length=500)),
                ('department', models.CharField(choices=[('Development', 'Development'), ('Designing', 'Designing'), ('Testing', 'Testing'), ('HR', 'HR')], max_length=25)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('education', models.TextField()),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics/')),
                ('document', models.FileField(blank=True, upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payslip', models.FileField(upload_to='payslips/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emp_management_app.attendance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emp_management_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_Title', models.CharField(max_length=500)),
                ('leave_type', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=10)),
                ('leave_from', models.DateField()),
                ('leave_to', models.DateField()),
                ('no_of_days', models.CharField(max_length=12)),
                ('status', models.CharField(choices=[('Development', 'Development'), ('Designing', 'Designing'), ('Testing', 'Testing'), ('HR', 'HR')], max_length=25)),
                ('halfday', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=5)),
                ('reason', models.TextField()),
                ('note', models.TextField()),
                ('apply_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emp_management_app.employee')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emp_management_app.employee'),
        ),
    ]
