# Generated by Django 4.2.2 on 2023-06-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_management_app', '0002_alter_leave_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='payslip',
            field=models.FileField(blank=True, upload_to='payslips/'),
        ),
    ]
