# Generated by Django 4.2.2 on 2023-06-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_management_app', '0003_alter_payroll_payslip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='break_time',
            new_name='break_in_time',
        ),
        migrations.AddField(
            model_name='attendance',
            name='break_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
