# Generated by Django 4.2.2 on 2023-06-13 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_management_app', '0004_rename_break_time_attendance_break_in_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_name', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('detials', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='leave',
            name='holiday',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Emp_management_app.holiday'),
        ),
    ]
