# Generated by Django 4.2.2 on 2023-06-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_management_app', '0008_alter_leave_halfday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='halfday',
            new_name='halfday_from',
        ),
        migrations.AddField(
            model_name='leave',
            name='halfday_to',
            field=models.CharField(blank=True, choices=[('First', 'First'), ('Second', 'Second')], max_length=10, null=True),
        ),
    ]
