# Generated by Django 4.2.2 on 2023-06-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_management_app', '0009_rename_halfday_leave_halfday_from_leave_halfday_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='halfday_from',
            field=models.BooleanField(blank=True, choices=[('First', 'First'), ('Second', 'Second')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='halfday_to',
            field=models.BooleanField(blank=True, choices=[('First', 'First'), ('Second', 'Second')], default=False, null=True),
        ),
    ]
