# Generated by Django 4.2.2 on 2023-06-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_management_app', '0011_alter_leave_halfday_from_alter_leave_halfday_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='my_field',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='halfday_from',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='halfday_to',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='First Half'),
        ),
    ]
