# Generated by Django 4.2.2 on 2023-06-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_management_app', '0012_leave_my_field_alter_leave_halfday_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='halfday_from',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='leave',
            name='halfday_to',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
