# Generated by Django 4.2.2 on 2023-06-14 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_management_app', '0013_alter_leave_halfday_from_alter_leave_halfday_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='my_field',
        ),
    ]
