# Generated by Django 4.2.2 on 2023-06-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_management_app', '0015_alter_leave_status_leave_yearly_leave_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_balance',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='leave_yearly',
            name='year',
            field=models.IntegerField(),
        ),
    ]
