# Generated by Django 4.2.2 on 2023-06-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_management_app', '0016_alter_leave_balance_year_alter_leave_yearly_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leave_Balance',
            new_name='Emp_Total_Leave',
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='halfday_from',
            new_name='first_half',
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='halfday_to',
            new_name='second_half',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='holiday',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='leave_type',
        ),
        migrations.RemoveField(
            model_name='leave_yearly',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='attendance',
        ),
    ]
